//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public Manufacturers()
        {
            this.Shoes = new HashSet<Shoes>();
        }
    
        public int ManufacturersID { get; set; }
        public string ManufacturersName { get; set; }
    
        public virtual ICollection<Shoes> Shoes { get; set; }
    }
}
