//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dem.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Manufacturers> Manufacturers { get; set; }
        public DbSet<OrderDetails> OrderDetails { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<PickupPoints> PickupPoints { get; set; }
        public DbSet<Roless> Roless { get; set; }
        public DbSet<Shoes> Shoes { get; set; }
        public DbSet<Statuses> Statuses { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<UnitMeasurements> UnitMeasurements { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
